### PR TITLE
API: Declare parameters const where applicable

### PR DESCRIPTION
**Pull request by gueraf**
see #41

### CODE REVIEW

**Comment by TomTheBear** [comment]
Hi,

Thanks for the PR. I only had time for a quick check and I cannot see any problematic changes. Have you checked all the functions or only the obvious ones (properly documented in Doxygen)? 

For your todos, the first one is a documentation error, it must be [in,out] and the second is a noop, I have to change these two lines. But I'll wait until we merged this PR.

As soon as I have time, I check your PR in detail and hopefully merge it.

**Comment by gueraf** [comment]
Hi,

thanks for reviewing the PR.

I only considered the methods declared in the header likwid.h and propagated changes to implementations if necessary; I think that all functions in likwid.h have Doxygen annotations.

If it helps I can go through the implementation of the internal methods in a separate PR and try to change the obvious ones, but I don't think that this adds any real benefit for users of the library. 

I will fix the documentation todo tomorrow and add the change to this PR. Do you want me to also remove the noop statements or should I leave the todo in place?

Cheers,
Fabian

**Comment by TomTheBear** [comment]
Hi,

I'm pretty sure that all function definitions in likwid.h have annotations, I'm not really motivated to document everything, but I forced myself for the likwid.h.

I don't think that we need the const internally. Especially as const function parameters are only used for error checking, no optimizations can be performed by the compiler.

You can remove the noop statements in your PR, that way I don't forget it afterwards. Thanks

Greetings,
Thomas

**Comment by gueraf** [comment]
Done.

**Comment by TomTheBear** [comment]
I checked your pull request again and it looks fine. I merge it into the master branch. Thank you.

**Pull request merged**
