### PR TITLE
Add function for manually writing marker file

### PR DESCRIPTION
**Pull request by OoJJBoO**
Add `likwid_writeMarkerFile` function to address the issue described in #583.

### CODE REVIEW

**Comment by TomTheBear** [comment]
Looks good, thanks for your work on the comments.

I found a small error in the F90 interface. The function in `likwid_f90_interface.c` has to have an underscore in the end: `likwid_writemarkerfile_`.

**Comment by OoJJBoO** [comment]
Updated. But looking at the other functions in the same file, I guess I should probably also use the way of copying the string first before passing it to the `likwid_writeMarkerFile` function, right? Didn't notice that earlier for some reason.

**Comment by TomTheBear** [comment]
Yes, you should copy the string before providing it to the C functions.

**Comment by OoJJBoO** [comment]
Okay, I changed it. I also added the missing register macro in the Lua bindings.

**Comment by TomTheBear** [comment]
Sorry that I didn't check more thoroughly. I'm on a business trip (SC23) and read your code in between meetings. Next week I have more time to go through your changes.

**Comment by OoJJBoO** [comment]
No worries, take your time :)

**Comment by TomTheBear** [comment]
I looked at your code again and I realized that the new functions/macros do not follow the current naming scheme:
- `likwid_writeMarkerFile` -> `likwid_markerWriteFile`
- `LIKWID_WRITE_MARKER_FILE` -> `LIKWID_MARKER_WRITE` or `LIKWID_MARKER_WRITE_FILE`
- `likwid_writemarkerfile_` -> `likwid_markerwritefile_`
- `lua_likwid_writeMarkerFile` -> `lua_likwid_markerWriteFile`

**Comment by OoJJBoO** [comment]
Ah, I see, you're right. I'll update them soon

**Comment by TomTheBear** [comment]
Thanks, that should be all functions for the CPU MarkerAPI.

I should probably add similar functions for the Nvidia MarkerAPI and the ROCm MarkerAPI.

**Pull request merged**
