### PR TITLE
Add check for event name duplicates

### PR DESCRIPTION
**Pull request by termim**
Please consider this PR which introduces checks for event names uniqueness.
Running the updated script as 
`<path_to_likwid>/test/check_events_files.py events -v
`
produces ~90 cases when the same name is used for events with different UMASK.

### CODE REVIEW

**Comment by TomTheBear** [comment]
Thanks for the PR. Such a script is very helpful.

I tried your script and got some problems. The first one was missing of the pyparsing module. Not the big deal. But after installing pyparsing the output is very limited (no output):
```
$ python3 check_events_files.py events -v
$
```

I tried the self test and one test fails:
```
$ python3 check_events_files.py self
======================================================================
ERROR: test_event (__main__.test_EventParser.<locals>.TestEventParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "check_events_files.py", line 291, in test_event
    res = self.parser.Evt.parseString("EVENT_C_LO_AD_CREDITS_EMPTY             0x22 RBOX0C0|RBOX0C1|RBOX1C0|RBOX1C1").asDict()
  File "/usr/local/lib/python3.6/dist-packages/pyparsing.py", line 1804, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.6/dist-packages/pyparsing.py", line 1581, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/usr/local/lib/python3.6/dist-packages/pyparsing.py", line 1203, in wrapper
    ret = func(*args[limit[0]:])
  File "check_events_files.py", line 140, in _set_event
    event_head.update(line_num = self.line_num)
AttributeError: 'EventParser' object has no attribute 'line_num'

----------------------------------------------------------------------
```

**Comment by TomTheBear** [comment]
Thanks, that fixed everything. I get output from the events command and the self tests work. Ready to merge.

**Comment by termim** [comment]
You probably run the script from outside of the likwid workspace. The default search path for the input files is ../src/include. I've added a warning to reduce confusion. Please see  #230.

**Comment by TomTheBear** [comment]
From the main directory, yes, so ../src/include of course failed.

**Comment by TomTheBear** [comment]
Is there a reason why the output is to stderr?

**Comment by termim** [comment]
> Is there a reason why the output is to stderr?

Errors are supposed to go to stderr, aren't they?

**Comment by TomTheBear** [comment]
OK, accepted. Have a nice weekend.

**Pull request merged**
