### PR TITLE
Add mperf, aperf and pperf for skylake

### PR DESCRIPTION
**Pull request by jimmysitu**
Hi, All

I add mperf/aperf/pperf counter for Intel skylake.

### CODE REVIEW

**Comment by TomTheBear** [comment]
Thanks for the PR. 

One thing is missing: You cannot use the events if built with perf_event backend. Since the units are named differently in LIKWID and perf_event, you have to add the appropriate relation in the `translate_types` for Skylake. Skylake currently uses the [default translation types](https://github.com/RRZE-HPC/likwid/blob/master/src/perfmon.c#L155-L166). You can copy the whole list and put it in `src/includes/perfmon_skylake_counters.h` (check other `*_counter.h` files for naming).

How about the other architectures? `src/includes/skylake.h` is also used for server class `skylakeX` but the PR only adds the events to the desktop class `skylake`. Are you willing to add the support to other architectures as well? When I remember corrently, the events are available since SandyBridge.

**Comment by TomTheBear** [comment]
This PR won't make it into the upcoming release. I don't want to add something for only one architecture and only with one access method. We have to generalize the support.

**Comment by jimmysitu** [comment]
> Thanks for the PR.
> 
> One thing is missing: You cannot use the events if built with perf_event backend. Since the units are named differently in LIKWID and perf_event, you have to add the appropriate relation in the `translate_types` for Skylake. Skylake currently uses the [default translation types](https://github.com/RRZE-HPC/likwid/blob/master/src/perfmon.c#L155-L166). You can copy the whole list and put it in `src/includes/perfmon_skylake_counters.h` (check other `*_counter.h` files for naming).
> 
> How about the other architectures? `src/includes/skylake.h` is also used for server class `skylakeX` but the PR only adds the events to the desktop class `skylake`. Are you willing to add the support to other architectures as well? When I remember corrently, the events are available since SandyBridge.

**Comment by jimmysitu** [comment]
Hi, @TomTheBear 

I'd like to help to make it support built with perf_event backend. And I followed the instructions you mention above.
But it seems I still missing something, and I only get all zero of mperf/aperf/pperf when using perf_event backend.
```bash
sudo likwid-perfctr -C 0 -g PERF sleep 5
```
```bash
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
CPU type:	Intel Kabylake processor
CPU clock:	1.90 GHz
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Group 1: PERF
+-----------------------+---------+--------+
|         Event         | Counter | Core 0 |
+-----------------------+---------+--------+
|   INSTR_RETIRED_ANY   |  FIXC0  | 247145 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  | 480119 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  | 253511 |
|         MPERF         |  MPERF  |      0 |
|         APERF         |  APERF  |      0 |
|         PPERF         |  PPERF  |      0 |
+-----------------------+---------+--------+

+----------------------+-----------+
|        Metric        |   Core 0  |
+----------------------+-----------+
|  Runtime (RDTSC) [s] |    5.0013 |
| Runtime unhalted [s] |    0.0003 |
|      Clock [MHz]     | 3590.7354 |
|          CPI         |    1.9427 |
|    Aperf/Mperf [%]   |     -     |
|    Pperf/Aperf [%]   |     -     |
+----------------------+-----------+
```

**Comment by TomTheBear** [comment]
Please run it like `likwid-perfctr -V 3 ...`. This should give you some information where the problem resides. And if you don't see anything, I can (hopefully) point you to the issue in the code.

**Comment by TomTheBear** [comment]
I took a look in your code changes and the problem might be your event definitions:
```
EVENT_MPERF      0x00   MPERF
UMASK_MPERF      0x00

EVENT_APERF      0x00   APERF
UMASK_APERF      0x00
```

If you look at the event definition provided by `perf_event`, the event ID is `0x02` on my Haswell desktop:
```
$ cat /sys/bus/event_source/devices/msr/events/mperf
event=0x02
```
`aperf` should have event ID `0x01`. I don't find the code for `pperf`, so it might not be provided by `perf_event` (or at least not on my Haswell system).

```
EVENT_MPERF      0x02   MPERF
UMASK_MPERF      0x00

EVENT_APERF      0x01   APERF
UMASK_APERF      0x00
```

**Comment by TomTheBear** [comment]
Do the new counters/event work now with perf_event? Thanks for creating a performance group.

**Comment by jimmysitu** [comment]
Hi, @TomTheBear 

They do not work yet, I try to debug a little while, but fail to find anything meaning full. I attached the -V 3 log here.
```bash
DEBUG - [hwloc_init_cpuInfo:358] HWLOC CpuInfo Family 6 Model 142 Stepping 10 Vendor 0x0 Part 0x0 isIntel 1 numHWThreads 8 activeHWThreads 8
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 0 Thread 0 Core 0 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 4 Thread 1 Core 0 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 1 Thread 0 Core 1 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 5 Thread 1 Core 1 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 2 Thread 0 Core 2 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 6 Thread 1 Core 2 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 3 Thread 0 Core 3 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 7 Thread 1 Core 3 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_cacheTopology:748] HWLOC Cache Pool ID 0 Level 1 Size 32768 Threads 2
DEBUG - [hwloc_init_cacheTopology:748] HWLOC Cache Pool ID 1 Level 2 Size 262144 Threads 2
DEBUG - [hwloc_init_cacheTopology:748] HWLOC Cache Pool ID 2 Level 3 Size 6291456 Threads 8
DEBUG - [affinity_init:304] Affinity: Socket domains 1
DEBUG - [affinity_init:312] Affinity: NUMA domains 1
DEBUG - [affinity_init:315] Affinity: CPUs per socket 8
DEBUG - [affinity_init:325] Affinity: CPU cores per LLC 4
DEBUG - [affinity_init:329] Affinity: CPUs per LLC 8
DEBUG - [affinity_init:336] Affinity: Cache domains 1
DEBUG - [affinity_init:340] Affinity: All domains 4
DEBUG - [affinity_init:353] Affinity domain N: 8 HW threads on 4 cores
DEBUG - [affinity_init:392] Affinity domain S0: 8 HW threads on 4 cores
DEBUG - [affinity_init:422] Affinity domain C0: 8 HW threads on 4 cores
DEBUG - [affinity_init:494] Affinity domain M0: 8 HW threads on 4 cores
DEBUG - [create_lookups:252] affinity_thread2core_lookup[0] = 0
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[0] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[0] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[0] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[1] = 1
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[1] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[1] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[1] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[2] = 2
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[2] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[2] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[2] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[3] = 3
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[3] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[3] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[3] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[4] = 0
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[4] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[4] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[4] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[5] = 1
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[5] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[5] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[5] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[6] = 2
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[6] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[6] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[6] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[7] = 3
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[7] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[7] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[7] = 0
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
CPU type:	Intel Kabylake processor
CPU clock:	1.89 GHz
CPU family:	6
CPU model:	142
CPU short:	skylake
CPU stepping:	10
CPU features:	FP ACPI MMX SSE SSE2 HTT TM RDTSCP MONITOR VMX EIST TM2 SSSE FMA SSE4.1 SSE4.2 AES AVX RDRAND HLE AVX2 RTM RDSEED SSE3 
CPU arch:	x86_64
--------------------------------------------------------------------------------
PERFMON version:	4
PERFMON number of counters:	4
PERFMON width of counters:	48
PERFMON number of fixed counters:	3
--------------------------------------------------------------------------------
[1;34m[likwid-pin] Main PID -> core 0 - OK[0m
Executing: sleep 10
DEBUG - [perfmon_addEventSet:2001] Currently 1 groups of 2 active
DEBUG - [perfgroup_readGroup:836] Cannot read group file /usr/local/share/likwid/perfgroups/skylake/PERF.txt. Trying /home/jmst/.likwid/groups/skylake/PERF.txt
DEBUG - [perfgroup_readGroup:852] Reading group PERF from /home/jmst/.likwid/groups/skylake/PERF.txt
DEBUG - [perfmon_addEventSet:2182] Added event INSTR_RETIRED_ANY for counter FIXC0 to group 0
DEBUG - [perfmon_addEventSet:2182] Added event CPU_CLK_UNHALTED_CORE for counter FIXC1 to group 0
DEBUG - [perfmon_addEventSet:2182] Added event CPU_CLK_UNHALTED_REF for counter FIXC2 to group 0
DEBUG - [perfmon_addEventSet:2182] Added event MPERF for counter MPERF to group 0
DEBUG - [perfmon_addEventSet:2182] Added event APERF for counter APERF to group 0
DEBUG - [perfmon_addEventSet:2182] Added event PPERF for counter PPERF to group 0
DEBUG - [perfmon_setupCountersThread_perfevent:648] SETUP_FIXED [0] Register 0x0 , Flags: 0x1 
DEBUG - [perfmon_setupCountersThread_perfevent:789] perf_event_open: cpu_id=0 pid=26931 flags=0
DEBUG - [perfmon_setupCountersThread_perfevent:648] SETUP_FIXED [0] Register 0x1 , Flags: 0x0 
DEBUG - [perfmon_setupCountersThread_perfevent:789] perf_event_open: cpu_id=0 pid=26931 flags=0
DEBUG - [perfmon_setupCountersThread_perfevent:648] SETUP_FIXED [0] Register 0x2 , Flags: 0x9 
DEBUG - [perfmon_setupCountersThread_perfevent:789] perf_event_open: cpu_id=0 pid=26931 flags=0
--------------------------------------------------------------------------------
DEBUG - [perfmon_startCountersThread_perfevent:828] RESET_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:839] START_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:828] RESET_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:839] START_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:828] RESET_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:839] START_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:886] FREEZE_COUNTER [0] Register 0x3 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:890] READ_COUNTER [0] Register 0x3 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:895] UNFREEZE_COUNTER [0] Register 0x3 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:886] FREEZE_COUNTER [0] Register 0x4 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:890] READ_COUNTER [0] Register 0x4 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:895] UNFREEZE_COUNTER [0] Register 0x4 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:886] FREEZE_COUNTER [0] Register 0x5 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:890] READ_COUNTER [0] Register 0x5 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:895] UNFREEZE_COUNTER [0] Register 0x5 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:858] FREEZE_COUNTER [0] Register 0x3 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:862] READ_COUNTER [0] Register 0x3 , Flags: 0x3C55F 
DEBUG - [perfmon_stopCountersThread_perfevent:868] RESET_COUNTER [0] Register 0x3 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:858] FREEZE_COUNTER [0] Register 0x4 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:862] READ_COUNTER [0] Register 0x4 , Flags: 0x6C15E 
DEBUG - [perfmon_stopCountersThread_perfevent:868] RESET_COUNTER [0] Register 0x4 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:858] FREEZE_COUNTER [0] Register 0x5 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:862] READ_COUNTER [0] Register 0x5 , Flags: 0x390D2 
DEBUG - [perfmon_stopCountersThread_perfevent:868] RESET_COUNTER [0] Register 0x5 , Flags: 0x0 
--------------------------------------------------------------------------------
Group 1: PERF
+-----------------------+---------+--------+
|         Event         | Counter | Core 0 |
+-----------------------+---------+--------+
|   INSTR_RETIRED_ANY   |  FIXC0  | 247135 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  | 442718 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  | 233682 |
|         MPERF         |  MPERF  |      0 |
|         APERF         |  APERF  |      0 |
|         PPERF         |  PPERF  |      0 |
+-----------------------+---------+--------+

+----------------------+-----------+
|        Metric        |   Core 0  |
+----------------------+-----------+
|  Runtime (RDTSC) [s] |   10.0067 |
| Runtime unhalted [s] |    0.0002 |
|      Clock [MHz]     | 3589.9065 |
|          CPI         |    1.7914 |
|    Aperf/Mperf [%]   |     -     |
|    Pperf/Aperf [%]   |     -     |
+----------------------+-----------+


```

**Comment by TomTheBear** [comment]
It looks like the `PERF` counters are never set up nor started or stopped by the perf_event backend. Similar to the architecture-specific files, there is a big switch-case statement in [`src/includes/perfmon_perfevent.h`](https://github.com/RRZE-HPC/likwid/blob/master/src/includes/perfmon_perfevent.h#L641)  to configure the counters. No changes in the start, stop or read functions required commonly.

**Comment by jimmysitu** [comment]
Hi, @TomTheBear 

It seems the PERF registers are setup, but all PERF is reading the same value. Any idea?

```bash
DEBUG - [hwloc_init_cpuInfo:358] HWLOC CpuInfo Family 6 Model 142 Stepping 10 Vendor 0x0 Part 0x0 isIntel 1 numHWThreads 8 activeHWThreads 8
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 0 Thread 0 Core 0 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 4 Thread 1 Core 0 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 1 Thread 0 Core 1 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 5 Thread 1 Core 1 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 2 Thread 0 Core 2 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 6 Thread 1 Core 2 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 3 Thread 0 Core 3 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:531] HWLOC Thread Pool PU 7 Thread 1 Core 3 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_cacheTopology:748] HWLOC Cache Pool ID 0 Level 1 Size 32768 Threads 2
DEBUG - [hwloc_init_cacheTopology:748] HWLOC Cache Pool ID 1 Level 2 Size 262144 Threads 2
DEBUG - [hwloc_init_cacheTopology:748] HWLOC Cache Pool ID 2 Level 3 Size 6291456 Threads 8
DEBUG - [affinity_init:304] Affinity: Socket domains 1
DEBUG - [affinity_init:312] Affinity: NUMA domains 1
DEBUG - [affinity_init:315] Affinity: CPUs per socket 8
DEBUG - [affinity_init:325] Affinity: CPU cores per LLC 4
DEBUG - [affinity_init:329] Affinity: CPUs per LLC 8
DEBUG - [affinity_init:336] Affinity: Cache domains 1
DEBUG - [affinity_init:340] Affinity: All domains 4
DEBUG - [affinity_init:353] Affinity domain N: 8 HW threads on 4 cores
DEBUG - [affinity_init:392] Affinity domain S0: 8 HW threads on 4 cores
DEBUG - [affinity_init:422] Affinity domain C0: 8 HW threads on 4 cores
DEBUG - [affinity_init:494] Affinity domain M0: 8 HW threads on 4 cores
DEBUG - [create_lookups:252] affinity_thread2core_lookup[0] = 0
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[0] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[0] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[0] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[1] = 1
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[1] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[1] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[1] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[2] = 2
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[2] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[2] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[2] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[3] = 3
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[3] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[3] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[3] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[4] = 0
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[4] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[4] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[4] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[5] = 1
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[5] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[5] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[5] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[6] = 2
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[6] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[6] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[6] = 0
DEBUG - [create_lookups:252] affinity_thread2core_lookup[7] = 3
DEBUG - [create_lookups:254] affinity_thread2socket_lookup[7] = 0
DEBUG - [create_lookups:268] affinity_thread2numa_lookup[7] = 0
DEBUG - [create_lookups:276] affinity_thread2sharedl3_lookup[7] = 0
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
CPU type:	Intel Kabylake processor
CPU clock:	1.90 GHz
CPU family:	6
CPU model:	142
CPU short:	skylake
CPU stepping:	10
CPU features:	FP ACPI MMX SSE SSE2 HTT TM RDTSCP MONITOR VMX EIST TM2 SSSE FMA SSE4.1 SSE4.2 AES AVX RDRAND HLE AVX2 RTM RDSEED SSE3 
CPU arch:	x86_64
--------------------------------------------------------------------------------
PERFMON version:	4
PERFMON number of counters:	4
PERFMON width of counters:	48
PERFMON number of fixed counters:	3
--------------------------------------------------------------------------------
[1;34m[likwid-pin] Main PID -> core 0 - OK[0m
Executing: sleep 10
DEBUG - [perfmon_addEventSet:2001] Currently 1 groups of 2 active
DEBUG - [perfgroup_readGroup:852] Reading group PERF from /usr/local/share/likwid/perfgroups/skylake/PERF.txt
DEBUG - [perfmon_addEventSet:2182] Added event INSTR_RETIRED_ANY for counter FIXC0 to group 0
DEBUG - [perfmon_addEventSet:2182] Added event CPU_CLK_UNHALTED_CORE for counter FIXC1 to group 0
DEBUG - [perfmon_addEventSet:2182] Added event CPU_CLK_UNHALTED_REF for counter FIXC2 to group 0
DEBUG - [perfmon_addEventSet:2182] Added event MPERF for counter MPERF to group 0
DEBUG - [perfmon_addEventSet:2182] Added event APERF for counter APERF to group 0
DEBUG - [perfmon_addEventSet:2182] Added event PPERF for counter PPERF to group 0
DEBUG - [perfmon_setupCountersThread_perfevent:652] SETUP_FIXED [0] Register 0x0 , Flags: 0x1 
DEBUG - [perfmon_setupCountersThread_perfevent:801] perf_event_open: cpu_id=0 pid=9613 flags=0
DEBUG - [perfmon_setupCountersThread_perfevent:652] SETUP_FIXED [0] Register 0x1 , Flags: 0x0 
DEBUG - [perfmon_setupCountersThread_perfevent:801] perf_event_open: cpu_id=0 pid=9613 flags=0
DEBUG - [perfmon_setupCountersThread_perfevent:652] SETUP_FIXED [0] Register 0x2 , Flags: 0x9 
DEBUG - [perfmon_setupCountersThread_perfevent:801] perf_event_open: cpu_id=0 pid=9613 flags=0
DEBUG - [perfmon_setupCountersThread_perfevent:660] SETUP_PERF [0] Register 0x22 , Flags: 0x0 
DEBUG - [perfmon_setupCountersThread_perfevent:801] perf_event_open: cpu_id=0 pid=9613 flags=0
DEBUG - [perfmon_setupCountersThread_perfevent:660] SETUP_PERF [0] Register 0x23 , Flags: 0x0 
DEBUG - [perfmon_setupCountersThread_perfevent:801] perf_event_open: cpu_id=0 pid=9613 flags=0
DEBUG - [perfmon_setupCountersThread_perfevent:660] SETUP_PERF [0] Register 0x24 , Flags: 0x0 
DEBUG - [perfmon_setupCountersThread_perfevent:801] perf_event_open: cpu_id=0 pid=9613 flags=0
--------------------------------------------------------------------------------
DEBUG - [perfmon_startCountersThread_perfevent:840] RESET_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:851] START_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:840] RESET_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:851] START_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:840] RESET_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:851] START_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:840] RESET_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:851] START_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:840] RESET_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:851] START_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:840] RESET_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_startCountersThread_perfevent:851] START_COUNTER [0] Register 0x0 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:898] FREEZE_COUNTER [0] Register 0x3 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:902] READ_COUNTER [0] Register 0x3 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:907] UNFREEZE_COUNTER [0] Register 0x3 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:898] FREEZE_COUNTER [0] Register 0x4 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:902] READ_COUNTER [0] Register 0x4 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:907] UNFREEZE_COUNTER [0] Register 0x4 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:898] FREEZE_COUNTER [0] Register 0x5 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:902] READ_COUNTER [0] Register 0x5 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:907] UNFREEZE_COUNTER [0] Register 0x5 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:898] FREEZE_COUNTER [0] Register 0x6 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:902] READ_COUNTER [0] Register 0x6 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:907] UNFREEZE_COUNTER [0] Register 0x6 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:898] FREEZE_COUNTER [0] Register 0x7 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:902] READ_COUNTER [0] Register 0x7 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:907] UNFREEZE_COUNTER [0] Register 0x7 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:898] FREEZE_COUNTER [0] Register 0x8 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:902] READ_COUNTER [0] Register 0x8 , Flags: 0x0 
DEBUG - [perfmon_readCountersThread_perfevent:907] UNFREEZE_COUNTER [0] Register 0x8 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:870] FREEZE_COUNTER [0] Register 0x3 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:874] READ_COUNTER [0] Register 0x3 , Flags: 0x3C562 
DEBUG - [perfmon_stopCountersThread_perfevent:880] RESET_COUNTER [0] Register 0x3 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:870] FREEZE_COUNTER [0] Register 0x4 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:874] READ_COUNTER [0] Register 0x4 , Flags: 0x6E64F 
DEBUG - [perfmon_stopCountersThread_perfevent:880] RESET_COUNTER [0] Register 0x4 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:870] FREEZE_COUNTER [0] Register 0x5 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:874] READ_COUNTER [0] Register 0x5 , Flags: 0x3A492 
DEBUG - [perfmon_stopCountersThread_perfevent:880] RESET_COUNTER [0] Register 0x5 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:870] FREEZE_COUNTER [0] Register 0x6 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:874] READ_COUNTER [0] Register 0x6 , Flags: 0x6E34E 
DEBUG - [perfmon_stopCountersThread_perfevent:880] RESET_COUNTER [0] Register 0x6 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:870] FREEZE_COUNTER [0] Register 0x7 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:874] READ_COUNTER [0] Register 0x7 , Flags: 0x6E34E 
DEBUG - [perfmon_stopCountersThread_perfevent:880] RESET_COUNTER [0] Register 0x7 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:870] FREEZE_COUNTER [0] Register 0x8 , Flags: 0x0 
DEBUG - [perfmon_stopCountersThread_perfevent:874] READ_COUNTER [0] Register 0x8 , Flags: 0x6E34E 
DEBUG - [perfmon_stopCountersThread_perfevent:880] RESET_COUNTER [0] Register 0x8 , Flags: 0x0 
--------------------------------------------------------------------------------
Group 1: PERF
+-----------------------+---------+--------+
|         Event         | Counter | Core 0 |
+-----------------------+---------+--------+
|   INSTR_RETIRED_ANY   |  FIXC0  | 247138 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  | 452175 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  | 238738 |
|         MPERF         |  MPERF  | 451406 |
|         APERF         |  APERF  | 451406 |
|         PPERF         |  PPERF  | 451406 |
+-----------------------+---------+--------+

+----------------------+-----------+
|        Metric        |   Core 0  |
+----------------------+-----------+
|  Runtime (RDTSC) [s] |   10.0023 |
| Runtime unhalted [s] |    0.0002 |
|      Clock [MHz]     | 3590.4569 |
|          CPI         |    1.8296 |
|    Aperf/Mperf [%]   |       100 |
|    Pperf/Aperf [%]   |       100 |
+----------------------+-----------+


```

**Comment by TomTheBear** [comment]
So for me the events have different values.
```
|         MPERF         |  MPERF  |  8220753215 |
|         APERF         |  APERF  | 10422493511 |
|         PPERF         |  PPERF  |  6048975638 |
```

I attached a patch how I would have integrated them. We could keep your version or switch to my version, up to you.
[PERF_perf_event.txt](https://github.com/RRZE-HPC/likwid/files/5647279/PERF_perf_event.txt)

**Comment by TomTheBear** [comment]
Thanks for your work.

**Pull request merged**
