### PR TITLE
Add support for Intel Rocketlake

### PR DESCRIPTION
**Pull request by TomTheBear**
Main contribution by @edisonchan , see issue #391

Intel Rocketlake is a "backport" of the Icelake performance monitoring but currently no public documentation available.

### CODE REVIEW

**Comment by TomTheBear** [comment]
I tested the TMA group on an Intel IcelakeSP system and all results looked reasonable.

**Comment by carstenbauer** [comment]
FWIW, my local test system for developing [LIKWID.jl](https://github.com/JuliaPerf/LIKWID.jl) has a Rocketlake CPU (11th Gen i7-11700K). Would be great to have this supported, even if only partially. Please let me know, if there is something that I can do on my side (running tests or similar).

**Comment by carstenbauer** [comment]
Alright, first time trying to use this branch. While I get

```
CPU name:       11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
CPU type:       Intel Rocketlake processor
```

I see a segmentation fault when trying to use `likwid-perfctr`:

```
# likwid.jl
using LIKWID
using LinearAlgebra

N = 100_000_000
a = 3.141f0
z = zeros(Float32, N)
x = rand(Float32, N)
y = rand(Float32, N)

function saxpy!(z,a,x,y)
    z .= a .* x .+ y
end

saxpy!(z,a,x,y)
LIKWID.Marker.startregion("saxpy!")
saxpy!(z,a,x,y)
LIKWID.Marker.stopregion("saxpy!")	
```

```
➜  crstnbr@cbserver likwid  likwid-perfctr -C 0 -g FLOPS_SP -m julia --project=. likwid.jl 
--------------------------------------------------------------------------------
CPU name:       11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
CPU type:       Intel Rocketlake processor
CPU clock:      3.60 GHz
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Segmentation fault (core dumped)
```

I went through the Julia file line by line to "debug" this. I can execute all commands with no issue. The segfault only appears when closing Julia, i.e. (I guess) when the marker output / file is generated.

Note that not using the Marker API at all works fine:

```
➜  crstnbr@cbserver likwid  likwid-perfctr -C 0 -g FLOPS_SP -m julia -e '1+1'
--------------------------------------------------------------------------------
CPU name:       11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
CPU type:       Intel Rocketlake processor
CPU clock:      3.60 GHz
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Marker API result file does not exist. This may happen if the application has not called LIKWID_MARKER_CLOSE.
```

**Comment by TomTheBear** [comment]
Please run it with `-V 3` on the command line with and without the MarkerAPI flag (`-m`) for `likwid-perfctr` and attach both outputs. The outputs are quite long, so attach it as files please.

**Comment by carstenbauer** [comment]
[output_marker.txt](https://github.com/RRZE-HPC/likwid/files/7117182/output_marker.txt)
[output_nomarker.txt](https://github.com/RRZE-HPC/likwid/files/7117183/output_nomarker.txt)

(Note that the actual segfault message for the marker case, i.e. `Segmentation fault (core dumped)`, is absent from the output file.)

**Pull request merged**
