### PR TITLE
allow external lua

### PR DESCRIPTION
**Pull request by davydden**
WIP, but internal `lua` seems to build for me on Ubuntu 16.04, so this part should be fine.

p.s. adding support of external libs in makefile-only packages is a grand royal PITA :smile: I have not tested it mostly because `lua` i have around is a static lib with, presumably, `-fPIC` flags. So it should be fine to use it in shared libraries, but I seriously don't know what else/how needs to be changed to support this usage case.

### CODE REVIEW

**Comment by davydden** [comment]
it's getting somewhere, with
```
LUA_INCLUDE_DIR = /usr/include/lua5.2/#NO SPACE
LUA_LIB_DIR = /usr/lib/x86_64-linux-gnu/#NO SPACE
LUA_LIB_NAME = lua5.2#NO SPACE
```
it links as expected against
```
$ ldd liblikwid.so 
	linux-vdso.so.1 =>  (0x00007ffe6a5f4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8f37ded000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8f37be5000)
	liblua5.2.so.0 => /usr/lib/x86_64-linux-gnu/liblua5.2.so.0 (0x00007f8f379b2000)
	liblikwid-hwloc.so.4.1 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8f37795000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8f373cb000)
	/lib64/ld-linux-x86-64.so.2 (0x000056185e42a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8f371c7000)
```
whereas with internal `lua` we have:
```
$ ldd liblikwid.so 
	linux-vdso.so.1 =>  (0x00007ffc9c383000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fecb5934000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fecb572c000)
	liblikwid-hwloc.so.4.1 => not found
	liblikwid-lua.so.4.1 => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fecb550e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fecb5144000)
	/lib64/ld-linux-x86-64.so.2 (0x000056094de3f000)
```

@TomTheBear there are still some things failing on Travis, I would appreciate if you could have a look at advise on how to fit the remaining issues.

**Comment by davydden** [comment]
@TomTheBear failures are
```
/home/travis/build.sh: /usr/local/bin/likwid-pin: /usr/local/bin/likwid-lua: bad interpreter: No such file or directory
/home/travis/build.sh: /usr/local/bin/likwid-perfctr: /usr/local/bin/likwid-lua: bad interpreter: No such file or directory
/usr/local/bin/likwid-bench: error while loading shared libraries: liblikwid-lua.so.4.1: cannot open shared object file: No such file or directory
```
but i don't quite see why this happens...

**Comment by TomTheBear** [comment]
Hi,
I think there was a failure in your sed commands. I got it running with Lua 5.1. I committed a patch to the master branch, so that the Lua interface is ready to be used with Lua 5.1 to 5.3

My other changes:
```
$ git diff make/config_defines.mk
diff --git a/make/config_defines.mk b/make/config_defines.mk
index 7a95106..fae3f87 100644
--- a/make/config_defines.mk
+++ b/make/config_defines.mk
@@ -11,13 +11,15 @@ DEFINES   += -DVERSION=$(VERSION)         \
                 -DLIKWIDSOCKETBASE=$(LIKWIDSOCKETBASE) \
                 -D_GNU_SOURCE
 
+CWD := $(PWD)
+CWD ?= .
 DYNAMIC_TARGET_LIB := liblikwid.so
 STATIC_TARGET_LIB := liblikwid.a
 # LUA:
 ifdef LUA_INCLUDE_DIR
 LUA_INTERNAL := false#NO SPACE
 else
-LUA_FOLDER := $(PWD)/ext/lua#NO SPACE
+LUA_FOLDER := ext/lua#NO SPACE
 LUA_INCLUDE_DIR := $(LUA_FOLDER)/includes#NO SPACE
 LUA_LIB_DIR := $(LUA_FOLDER)#NO SPACE
 LUA_LIB_NAME := likwid-lua#NO SPACE
@@ -67,19 +69,11 @@ CFLAGS += $(SHARED_CFLAGS)
 LIBS += -L. -pthread -lm -ldl
 TARGET_LIB := $(DYNAMIC_TARGET_LIB)
 TARGET_HWLOC_LIB=$(HWLOC_FOLDER)/$(SHARED_LIBHWLOC)
-ifeq ($(LUA_INTERNAL),true)
 TARGET_LUA_LIB=$(LUA_LIB_DIR)/$(SHARED_LIBLUA)
 else
-TARGET_LUA_LIB=
-endif
-else
 TARGET_LIB := $(STATIC_TARGET_LIB)
 TARGET_HWLOC_LIB=$(HWLOC_FOLDER)/$(STATIC_LIBHWLOC)
-ifeq ($(LUA_INTERNAL),true)
 TARGET_LUA_LIB=$(LUA_LIB_DIR)/$(STATIC_LIBLUA)
-else
-TARGET_LUA_LIB=
-endif
 endif
 
 ifeq ($(HAS_SCHEDAFFINITY),1)
```
and
```
$ git diff Makefile
diff --git a/Makefile b/Makefile
index 5df35db..2002209 100644
--- a/Makefile
+++ b/Makefile
@@ -113,14 +113,14 @@ docs:
 $(L_APPS):  $(addprefix $(SRC_DIR)/applications/,$(addsuffix  .lua,$(L_APPS)))
        @echo "===>  ADJUSTING  $@"
        @if [ "$(ACCESSMODE)" = "direct" ]; then sed -i -e s/"access_mode = 1"/"access_mode = 0"/g $(SRC_DIR)/applications/$@.lua;fi
-       @if [ "$(LUA_INTERNAL)" = "false"]; then \
-               @sed -e s/'<INSTALLED_BINPREFIX>'\\/likwid-lua/$(subst /,\\/,$(INSTALLED_BINPREFIX))\\/$(LUA_LIB_NAME)/g; \
-       fi
        @sed -e s/'<INSTALLED_BINPREFIX>'/$(subst /,\\/,$(INSTALLED_BINPREFIX))/g \
                -e s/'<INSTALLED_PREFIX>'/$(subst /,\\/,$(INSTALLED_PREFIX))/g \
                -e s/'<VERSION>'/$(VERSION).$(RELEASE)/g \
                -e s/'<DATE>'/$(DATE)/g \
                $(addprefix $(SRC_DIR)/applications/,$(addsuffix  .lua,$@)) > $@
+       @if [ "$(LUA_INTERNAL)" = "false" ]; then \
+               sed -i -e s+"$(subst /,\\/,$(INSTALLED_BINPREFIX))/likwid-lua"+"/usr/bin/$(LUA_LIB_NAME)"+ $@; \
+       fi
        @if [ "$(ACCESSMODE)" = "direct" ]; then sed -i -e s/"access_mode = 0"/"access_mode = 1"/g $(SRC_DIR)/applications/$@.lua;fi
 
 $(L_HELPER):
@@ -327,8 +327,8 @@ install: install_daemon install_freq
        @for APP in $(C_APPS); do \
                install -m 755 $$APP  $(BINPREFIX); \
        done
-       @if [ "$(LUA_INTERNAL)" = "true"]; then \
-               @install -m 755 ext/lua/lua $(BINPREFIX)/$(LUA_LIB_NAME); \
+       @if [ "$(LUA_INTERNAL)" = "true" ]; then \
+               install -m 755 ext/lua/lua $(BINPREFIX)/$(LUA_LIB_NAME); \
        fi
        @echo "===> INSTALL helper applications to $(BINPREFIX)"
        @install -m 755 perl/feedGnuplot $(BINPREFIX)
@@ -342,8 +342,8 @@ install: install_daemon install_freq
        @install -m 755 $(TARGET_LIB) $(LIBPREFIX)/$(TARGET_LIB).$(VERSION).$(RELEASE)
        @install -m 755 liblikwidpin.so $(LIBPREFIX)/liblikwidpin.so.$(VERSION).$(RELEASE)
        @install -m 755 $(TARGET_HWLOC_LIB) $(LIBPREFIX)/$(shell basename $(TARGET_HWLOC_LIB)).$(VERSION).$(RELEASE)
-       @if [ "$(LUA_INTERNAL)" = "true"]; then \
-               @install -m 755 $(TARGET_LUA_LIB) $(LIBPREFIX)/$(shell basename $(TARGET_LUA_LIB)).$(VERSION).$(RELEASE); \
+       @if [ "$(LUA_INTERNAL)" = "true" ]; then \
+               install -m 755 $(TARGET_LUA_LIB) $(LIBPREFIX)/$(shell basename $(TARGET_LUA_LIB)).$(VERSION).$(RELEASE); \
        fi
        @cd $(LIBPREFIX) && ln -fs $(TARGET_LIB).$(VERSION).$(RELEASE) $(TARGET_LIB)
        @cd $(LIBPREFIX) && ln -fs $(TARGET_LIB).$(VERSION).$(RELEASE) $(TARGET_LIB).$(VERSION)
@@ -351,9 +351,9 @@ install: install_daemon install_freq
        @cd $(LIBPREFIX) && ln -fs $(PINLIB).$(VERSION).$(RELEASE) $(PINLIB).$(VERSION)
        @cd $(LIBPREFIX) && ln -fs $(shell basename $(TARGET_HWLOC_LIB)).$(VERSION).$(RELEASE) $(shell basename $(TARGET_HWLOC_LIB))
        @cd $(LIBPREFIX) && ln -fs $(shell basename $(TARGET_HWLOC_LIB)).$(VERSION).$(RELEASE) $(shell basename $(TARGET_HWLOC_LIB)).$(VERSION)
-       @if [ "$(LUA_INTERNAL)" = "true"]; then \
-               @cd $(LIBPREFIX) && ln -fs $(shell basename $(TARGET_LUA_LIB)).$(VERSION).$(RELEASE) $(shell basename $(TARGET_LUA_LIB)); \
-               @cd $(LIBPREFIX) && ln -fs $(shell basename $(TARGET_LUA_LIB)).$(VERSION).$(RELEASE) $(shell basename $(TARGET_LUA_LIB)).$(VERSION); \
+       @if [ "$(LUA_INTERNAL)" = "true" ]; then \
+               cd $(LIBPREFIX) && ln -fs $(shell basename $(TARGET_LUA_LIB)).$(VERSION).$(RELEASE) $(shell basename $(TARGET_LUA_LIB)); \
+               cd $(LIBPREFIX) && ln -fs $(shell basename $(TARGET_LUA_LIB)).$(VERSION).$(RELEASE) $(shell basename $(TARGET_LUA_LIB)).$(VERSION); \
        fi
        @echo "===> INSTALL man pages to $(MANPREFIX)/man1"
        @mkdir -p $(MANPREFIX)/man1
```

**Comment by TomTheBear** [comment]
Congrats. Keep in mind that the Travis-CI test run uses the default configuration without system Lua. If you want to test it with system Lua you have to adjust .travis.yaml to install Lua and to update `config.mk`

**Comment by davydden** [comment]
there are still some issues with system's lua
```
bash: _install/bin/likwid-pin: /usr/local/bin/likwid-lua: bad interpreter: No such file or directory
```
Looks like something somewhere is not `sed`-ed properly.

**Comment by TomTheBear** [comment]
I don't get the error. I tried Lua 5.1 (with commit https://github.com/RRZE-HPC/likwid/commit/e13d4c35bf03b0a3339f2ead453b3dbea3dcdf17 from master branch for 5.1 compatibility) and Lua 5.2 and both work fine.

**Comment by davydden** [comment]
for me the installed scripts like `likwid-pin` still have
```
#!/usr/local/bin/likwid-lua
```
I don't even know where from `/usr/local/bin` come, as I had
```
LUA_INCLUDE_DIR = /usr/include/lua5.2#NO SPACE
LUA_LIB_DIR = /usr/lib/x86_64-linux-gnu#NO SPACE
LUA_LIB_NAME = lua5.2#NO SPACE, executable is assumed to have the same name
LUA_BIN = /usr/bin#NO SPACE
```

**Comment by davydden** [comment]
looking at `$(L_APPS)`, i never see in the logs `@echo "===>  ADJUSTING  $@"`. Is there something more than just
```
make
make install
```
?

**Comment by davydden** [comment]
Anyway, if you tested it and it works, i must be doing something wrong here. Feel free to merge this PR.

**Comment by davydden** [comment]
@TomTheBear works! That's because i did not clean it and `make` was not updating `likwid-pin` and alike.

**Comment by davydden** [comment]
ldd looks right as well:
```
$ ldd _install/lib/liblikwid.so
	linux-vdso.so.1 =>  (0x00007ffdd556d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6e35e57000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6e35c4f000)
	liblua5.2.so.0 => /usr/lib/x86_64-linux-gnu/liblua5.2.so.0 (0x00007f6e35a1c000)
	liblikwid-hwloc.so.4.1 => /home/davydden/libs/likwid/_install/lib/liblikwid-hwloc.so.4.1 (0x00007f6e357eb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6e355ce000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6e35204000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559f580f8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6e35000000)
```

**Pull request merged**
